repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      [
        { id: check-yaml },
        { id: end-of-file-fixer },
        { id: trailing-whitespace },
      ]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      [
        { id: terraform_fmt },
        { id: terraform_validate },
        { id: terraform_tflint },
      ]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks: [{ id: shellcheck }]
  - repo: https://github.com/pycqa/ruff-pre-commit
    rev: v0.6.9
    hooks: [{ id: ruff }]
