[tool.poetry]
name = "securestack"
version = "0.1.0"
packages = [{ include = "securestack", from = "cli" }]

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12"

[tool.poetry.scripts]
securestack = "securestack.__main__:app"
